/*
 * Copyright 2023 ZF Friedrichshafen AG
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef RPCFUNCBLACKBOARD_H
#define RPCFUNCBLACKBOARD_H


#include <stdint.h>

#if defined SCRPCDLL_EXPORTS
#include "XilEnvRpc.h"        // Wenn vom der RPC DLL/Library verwendet neheme diesen Header
#else
#ifndef SC2PY_EXPORTS
#include "Blackboard.h"  // Ansonsten diesen
#endif
#endif

#include "RpcFuncBase.h"

#ifdef _WIN32
#ifdef __GNUC__
#pragma ms_struct on
#endif
#endif
#pragma pack(push,1)

#define BLACKBOARD_CMD_OFFSET  100


#define RPC_API_ADD_BBVARI_CMD         (BLACKBOARD_CMD_OFFSET+0)
typedef struct {
#define RPC_API_ADD_BBVARI_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetLabel;\
    int32_t Type;\
    int32_t OffsetUnit;\
    char Data[1];  // > 1Byte!
    RPC_API_ADD_BBVARI_MESSAGE_MEMBERS
} RPC_API_ADD_BBVARI_MESSAGE;

typedef struct {
#define RPC_API_ADD_BBVARI_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_ADD_BBVARI_MESSAGE_ACK_MEMBERS
} RPC_API_ADD_BBVARI_MESSAGE_ACK;

#define RPC_API_REMOVE_BBVARI_CMD         (BLACKBOARD_CMD_OFFSET+1)
typedef struct {
#define RPC_API_REMOVE_BBVARI_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
RPC_API_REMOVE_BBVARI_MESSAGE_MEMBERS
} RPC_API_REMOVE_BBVARI_MESSAGE;

typedef struct {
#define RPC_API_REMOVE_BBVARI_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
RPC_API_REMOVE_BBVARI_MESSAGE_ACK_MEMBERS
} RPC_API_REMOVE_BBVARI_MESSAGE_ACK;

#define RPC_API_ATTACH_BBVARI_CMD         (BLACKBOARD_CMD_OFFSET+2)
typedef struct {
#define RPC_API_ATTACH_BBVARI_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetLabel;\
    char Data[1];  // > 1Byte!
    RPC_API_ATTACH_BBVARI_MESSAGE_MEMBERS
} RPC_API_ATTACH_BBVARI_MESSAGE;

typedef struct {
#define RPC_API_ATTACH_BBVARI_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_ATTACH_BBVARI_MESSAGE_ACK_MEMBERS
} RPC_API_ATTACH_BBVARI_MESSAGE_ACK;

#define RPC_API_GET_CMD         (BLACKBOARD_CMD_OFFSET+3)
typedef struct {
#define RPC_API_GET_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_MESSAGE_MEMBERS
} RPC_API_GET_MESSAGE;

typedef struct {
#define RPC_API_GET_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    double ReturnValue;
    RPC_API_GET_MESSAGE_ACK_MEMBERS
} RPC_API_GET_MESSAGE_ACK;

#define RPC_API_GET_PHYS_CMD         (BLACKBOARD_CMD_OFFSET+4)
typedef struct {
#define RPC_API_GET_PHYS_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_PHYS_MESSAGE_MEMBERS
} RPC_API_GET_PHYS_MESSAGE;

typedef struct {
#define RPC_API_GET_PHYS_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    double ReturnValue;
    RPC_API_GET_PHYS_MESSAGE_ACK_MEMBERS
} RPC_API_GET_PHYS_MESSAGE_ACK;

#define RPC_API_SET_CMD         (BLACKBOARD_CMD_OFFSET+5)
typedef struct {
#define RPC_API_SET_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    double Value;
    RPC_API_SET_MESSAGE_MEMBERS
} RPC_API_SET_MESSAGE;

typedef struct {
#define RPC_API_SET_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_MESSAGE_ACK_MEMBERS
} RPC_API_SET_MESSAGE_ACK;

#define RPC_API_SET_PHYS_CMD         (BLACKBOARD_CMD_OFFSET+6)
typedef struct {
#define RPC_API_SET_PHYS_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    double Value;
    RPC_API_SET_PHYS_MESSAGE_MEMBERS
} RPC_API_SET_PHYS_MESSAGE;

typedef struct {
#define RPC_API_SET_PHYS_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_PHYS_MESSAGE_ACK_MEMBERS
} RPC_API_SET_PHYS_MESSAGE_ACK;

#define RPC_API_EQU_CMD         (BLACKBOARD_CMD_OFFSET+7)
typedef struct {
#define RPC_API_EQU_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetEquation;\
    char Data[1];  // > 1Byte!
    RPC_API_EQU_MESSAGE_MEMBERS
} RPC_API_EQU_MESSAGE;

typedef struct {
#define RPC_API_EQU_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    double ReturnValue;
    RPC_API_EQU_MESSAGE_ACK_MEMBERS
} RPC_API_EQU_MESSAGE_ACK;

#define RPC_API_WR_VARI_ENABLE_CMD         (BLACKBOARD_CMD_OFFSET+8)
typedef struct {
#define RPC_API_WR_VARI_ENABLE_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetLabel;\
    int32_t OffsetProcess;\
    char Data[1];  // > 1Byte!
    RPC_API_WR_VARI_ENABLE_MESSAGE_MEMBERS
} RPC_API_WR_VARI_ENABLE_MESSAGE;

typedef struct {
#define RPC_API_WR_VARI_ENABLE_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_WR_VARI_ENABLE_MESSAGE_ACK_MEMBERS
} RPC_API_WR_VARI_ENABLE_MESSAGE_ACK;

#define RPC_API_WR_VARI_DISABLE_CMD         (BLACKBOARD_CMD_OFFSET+9)
typedef struct {
#define RPC_API_WR_VARI_DISABLE_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetLabel;\
    int32_t OffsetProcess;\
    char Data[1];  // > 1Byte!
    RPC_API_WR_VARI_DISABLE_MESSAGE_MEMBERS
} RPC_API_WR_VARI_DISABLE_MESSAGE;

typedef struct {
#define RPC_API_WR_VARI_DISABLE_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_WR_VARI_DISABLE_MESSAGE_ACK_MEMBERS
} RPC_API_WR_VARI_DISABLE_MESSAGE_ACK;

#define RPC_API_IS_WR_VARI_ENABLED_CMD         (BLACKBOARD_CMD_OFFSET+10)
typedef struct {
#define RPC_API_IS_WR_VARI_ENABLED_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetLabel;\
    int32_t OffsetProcess;\
    char Data[1];  // > 1Byte!
    RPC_API_IS_WR_VARI_ENABLED_MESSAGE_MEMBERS
} RPC_API_IS_WR_VARI_ENABLED_MESSAGE;

typedef struct {
#define RPC_API_IS_WR_VARI_ENABLED_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_IS_WR_VARI_ENABLED_MESSAGE_ACK_MEMBERS
} RPC_API_IS_WR_VARI_ENABLED_MESSAGE_ACK;

#define RPC_API_LOAD_REF_LIST_CMD         (BLACKBOARD_CMD_OFFSET+11)
typedef struct {
#define RPC_API_LOAD_REF_LIST_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetRefList;\
    int32_t OffsetProcess;\
    char Data[1];  // > 1Byte!
    RPC_API_LOAD_REF_LIST_MESSAGE_MEMBERS
} RPC_API_LOAD_REF_LIST_MESSAGE;

typedef struct {
#define RPC_API_LOAD_REF_LIST_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_LOAD_REF_LIST_MESSAGE_ACK_MEMBERS
} RPC_API_LOAD_REF_LIST_MESSAGE_ACK;

#define RPC_API_ADD_REF_LIST_CMD         (BLACKBOARD_CMD_OFFSET+40)
typedef struct {
#define RPC_API_ADD_REF_LIST_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
        int32_t OffsetRefList;\
        int32_t OffsetProcess;\
        char Data[1];  // > 1Byte!
    RPC_API_ADD_REF_LIST_MESSAGE_MEMBERS
} RPC_API_ADD_REF_LIST_MESSAGE;

typedef struct {
#define RPC_API_ADD_REF_LIST_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_ADD_REF_LIST_MESSAGE_ACK_MEMBERS
} RPC_API_ADD_REF_LIST_MESSAGE_ACK;

#define RPC_API_SAVE_REF_LIST_CMD         (BLACKBOARD_CMD_OFFSET+12)
typedef struct {
#define RPC_API_SAVE_REF_LIST_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetRefList;\
    int32_t OffsetProcess;\
    char Data[1];  // > 1Byte!
    RPC_API_SAVE_REF_LIST_MESSAGE_MEMBERS
} RPC_API_SAVE_REF_LIST_MESSAGE;

typedef struct {
#define RPC_API_SAVE_REF_LIST_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SAVE_REF_LIST_MESSAGE_ACK_MEMBERS
} RPC_API_SAVE_REF_LIST_MESSAGE_ACK;

#define RPC_API_GET_VARI_CONVERSION_TYPE_CMD         (BLACKBOARD_CMD_OFFSET+14)
typedef struct {
#define RPC_API_GET_VARI_CONVERSION_TYPE_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_CONVERSION_TYPE_MESSAGE_MEMBERS
} RPC_API_GET_VARI_CONVERSION_TYPE_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_CONVERSION_TYPE_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_GET_VARI_CONVERSION_TYPE_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_CONVERSION_TYPE_MESSAGE_ACK;

#define RPC_API_GET_VARI_CONVERSION_STRING_CMD         (BLACKBOARD_CMD_OFFSET+15)
typedef struct {
#define RPC_API_GET_VARI_CONVERSION_STRING_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_CONVERSION_STRING_MESSAGE_MEMBERS
} RPC_API_GET_VARI_CONVERSION_STRING_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_CONVERSION_STRING_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t OffsetConversionString;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_VARI_CONVERSION_STRING_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_CONVERSION_STRING_MESSAGE_ACK;

#define RPC_API_SET_VARI_CONVERSION_CMD         (BLACKBOARD_CMD_OFFSET+16)
typedef struct {
#define RPC_API_SET_VARI_CONVERSION_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    int32_t Type;\
    int32_t OffsetConversionString;\
    char Data[1];  // > 1Byte!
    RPC_API_SET_VARI_CONVERSION_MESSAGE_MEMBERS
} RPC_API_SET_VARI_CONVERSION_MESSAGE;

typedef struct {
#define RPC_API_SET_VARI_CONVERSION_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_VARI_CONVERSION_MESSAGE_ACK_MEMBERS
} RPC_API_SET_VARI_CONVERSION_MESSAGE_ACK;

#define RPC_API_GET_VARI_TYPE_CMD         (BLACKBOARD_CMD_OFFSET+17)
typedef struct {
#define RPC_API_GET_VARI_TYPE_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_TYPE_MESSAGE_MEMBERS
} RPC_API_GET_VARI_TYPE_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_TYPE_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_GET_VARI_TYPE_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_TYPE_MESSAGE_ACK;

#define RPC_API_GET_VARI_UNIT_CMD         (BLACKBOARD_CMD_OFFSET+18)
typedef struct {
#define RPC_API_GET_VARI_UNIT_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_UNIT_MESSAGE_MEMBERS
} RPC_API_GET_VARI_UNIT_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_UNIT_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t OffsetUnit;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_VARI_UNIT_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_UNIT_MESSAGE_ACK;

#define RPC_API_SET_VARI_UNIT_CMD         (BLACKBOARD_CMD_OFFSET+19)
typedef struct {
#define RPC_API_SET_VARI_UNIT_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    int32_t OffsetUnit;\
    char Data[1];  // > 1Byte!
    RPC_API_SET_VARI_UNIT_MESSAGE_MEMBERS
} RPC_API_SET_VARI_UNIT_MESSAGE;

typedef struct {
#define RPC_API_SET_VARI_UNIT_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_VARI_UNIT_MESSAGE_ACK_MEMBERS
} RPC_API_SET_VARI_UNIT_MESSAGE_ACK;

#define RPC_API_GET_VARI_MIN_CMD         (BLACKBOARD_CMD_OFFSET+20)
typedef struct {
#define RPC_API_GET_VARI_MIN_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_MIN_MESSAGE_MEMBERS
} RPC_API_GET_VARI_MIN_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_MIN_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    double ReturnValue;
    RPC_API_GET_VARI_MIN_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_MIN_MESSAGE_ACK;

#define RPC_API_GET_VARI_MAX_CMD         (BLACKBOARD_CMD_OFFSET+21)
typedef struct {
#define RPC_API_GET_VARI_MAX_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_MAX_MESSAGE_MEMBERS
} RPC_API_GET_VARI_MAX_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_MAX_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    double ReturnValue;
    RPC_API_GET_VARI_MAX_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_MAX_MESSAGE_ACK;

#define RPC_API_SET_VARI_MIN_CMD         (BLACKBOARD_CMD_OFFSET+22)
typedef struct {
#define RPC_API_SET_VARI_MIN_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    double Min;
    RPC_API_SET_VARI_MIN_MESSAGE_MEMBERS
} RPC_API_SET_VARI_MIN_MESSAGE;

typedef struct {
#define RPC_API_SET_VARI_MIN_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_VARI_MIN_MESSAGE_ACK_MEMBERS
} RPC_API_SET_VARI_MIN_MESSAGE_ACK;

#define RPC_API_SET_VARI_MAX_CMD         (BLACKBOARD_CMD_OFFSET+23)
typedef struct {
#define RPC_API_SET_VARI_MAX_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    double Max;
    RPC_API_SET_VARI_MAX_MESSAGE_MEMBERS
} RPC_API_SET_VARI_MAX_MESSAGE;

typedef struct {
#define RPC_API_SET_VARI_MAX_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_VARI_MAX_MESSAGE_ACK_MEMBERS
} RPC_API_SET_VARI_MAX_MESSAGE_ACK;

#define RPC_API_GET_NEXT_VARI_CMD         (BLACKBOARD_CMD_OFFSET+24)
typedef struct {
#define RPC_API_GET_NEXT_VARI_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Flag;\
    int32_t OffsetFilter;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_NEXT_VARI_MESSAGE_MEMBERS
} RPC_API_GET_NEXT_VARI_MESSAGE;

typedef struct {
#define RPC_API_GET_NEXT_VARI_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t OffsetLabel;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_NEXT_VARI_MESSAGE_ACK_MEMBERS
} RPC_API_GET_NEXT_VARI_MESSAGE_ACK;

#define RPC_API_GET_NEXT_VARI_EX_CMD         (BLACKBOARD_CMD_OFFSET+25)
typedef struct {
#define RPC_API_GET_NEXT_VARI_EX_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Flag;\
    int32_t OffsetFilter;\
    int32_t OffsetProcess;\
    int32_t AccessFlags;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_NEXT_VARI_EX_MESSAGE_MEMBERS
} RPC_API_GET_NEXT_VARI_EX_MESSAGE;

typedef struct {
#define RPC_API_GET_NEXT_VARI_EX_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t OffsetLabel;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_NEXT_VARI_EX_MESSAGE_ACK_MEMBERS
} RPC_API_GET_NEXT_VARI_EX_MESSAGE_ACK;

#define RPC_API_GET_VARI_ENUM_CMD         (BLACKBOARD_CMD_OFFSET+26)
typedef struct {
#define RPC_API_GET_VARI_ENUM_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    double Value;
    RPC_API_GET_VARI_ENUM_MESSAGE_MEMBERS
} RPC_API_GET_VARI_ENUM_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_ENUM_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t OffsetEnum;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_VARI_ENUM_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_ENUM_MESSAGE_ACK;

#define RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_CMD         (BLACKBOARD_CMD_OFFSET+27)
typedef struct {
#define RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_MESSAGE_MEMBERS
} RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_DISPLAY_FORMAT_WIDTH_MESSAGE_ACK;

#define RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_CMD         (BLACKBOARD_CMD_OFFSET+28)
typedef struct {
#define RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;
    RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_MESSAGE_MEMBERS
} RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_MESSAGE;

typedef struct {
#define RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_MESSAGE_ACK_MEMBERS
} RPC_API_GET_VARI_DISPLAY_FORMAT_PREC_MESSAGE_ACK;

#define RPC_API_SET_VARI_DISPLAY_FORMAT_CMD         (BLACKBOARD_CMD_OFFSET+29)
typedef struct {
#define RPC_API_SET_VARI_DISPLAY_FORMAT_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Vid;\
    int32_t Width;\
    int32_t Prec;
    RPC_API_SET_VARI_DISPLAY_FORMAT_MESSAGE_MEMBERS
} RPC_API_SET_VARI_DISPLAY_FORMAT_MESSAGE;

typedef struct {
#define RPC_API_SET_VARI_DISPLAY_FORMAT_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_VARI_DISPLAY_FORMAT_MESSAGE_ACK_MEMBERS
} RPC_API_SET_VARI_DISPLAY_FORMAT_MESSAGE_ACK;

#define RPC_API_IMPORT_VARI_PROPERTIES_CMD         (BLACKBOARD_CMD_OFFSET+30)
typedef struct {
#define RPC_API_IMPORT_VARI_PROPERTIES_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetFilename;\
    char Data[1];  // > 1Byte!
    RPC_API_IMPORT_VARI_PROPERTIES_MESSAGE_MEMBERS
} RPC_API_IMPORT_VARI_PROPERTIES_MESSAGE;

typedef struct {
#define RPC_API_IMPORT_VARI_PROPERTIES_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_IMPORT_VARI_PROPERTIES_MESSAGE_ACK_MEMBERS
} RPC_API_IMPORT_VARI_PROPERTIES_MESSAGE_ACK;

#define RPC_API_ENABLE_RANGE_CONTROL_CMD         (BLACKBOARD_CMD_OFFSET+31)
typedef struct {
#define RPC_API_ENABLE_RANGE_CONTROL_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetProcessNameFilter;\
    int32_t OffsetVariableNameFilter;\
    char Data[1];  // > 1Byte!
    RPC_API_ENABLE_RANGE_CONTROL_MESSAGE_MEMBERS
} RPC_API_ENABLE_RANGE_CONTROL_MESSAGE;

typedef struct {
#define RPC_API_ENABLE_RANGE_CONTROL_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_ENABLE_RANGE_CONTROL_MESSAGE_ACK_MEMBERS
} RPC_API_ENABLE_RANGE_CONTROL_MESSAGE_ACK;

#define RPC_API_DISABLE_RANGE_CONTROL_CMD         (BLACKBOARD_CMD_OFFSET+32)
typedef struct {
#define RPC_API_DISABLE_RANGE_CONTROL_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetProcessNameFilter;\
    int32_t OffsetVariableNameFilter;\
    char Data[1];  // > 1Byte!
    RPC_API_DISABLE_RANGE_CONTROL_MESSAGE_MEMBERS
} RPC_API_DISABLE_RANGE_CONTROL_MESSAGE;

typedef struct {
#define RPC_API_DISABLE_RANGE_CONTROL_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_DISABLE_RANGE_CONTROL_MESSAGE_ACK_MEMBERS
} RPC_API_DISABLE_RANGE_CONTROL_MESSAGE_ACK;

#define RPC_API_WRITE_FRAME_CMD         (BLACKBOARD_CMD_OFFSET+33)
typedef struct {
#define RPC_API_WRITE_FRAME_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Offset_int32_Elements_Vids;\
    int32_t Offset_int8_Elements_PhysOrRaw;\
    int32_t Offset_double_Elements_ValueFrame;\
    int32_t Elements;\
    char Data[1];  // > 1Byte!
    RPC_API_WRITE_FRAME_MESSAGE_MEMBERS
} RPC_API_WRITE_FRAME_MESSAGE;

typedef struct {
#define RPC_API_WRITE_FRAME_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_WRITE_FRAME_MESSAGE_ACK_MEMBERS
} RPC_API_WRITE_FRAME_MESSAGE_ACK;

#define RPC_API_GET_FRAME_CMD         (BLACKBOARD_CMD_OFFSET+34)
typedef struct {
#define RPC_API_GET_FRAME_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Offset_int32_Elements_Vids;\
    int32_t Offset_int8_Elements_PhysOrRaw;\
    int32_t Elements;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_FRAME_MESSAGE_MEMBERS
} RPC_API_GET_FRAME_MESSAGE;

typedef struct {
#define RPC_API_GET_FRAME_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t Offset_double_Elements_ValueFrame;\
    int32_t Elements;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_FRAME_MESSAGE_ACK_MEMBERS
} RPC_API_GET_FRAME_MESSAGE_ACK;

#define RPC_API_WRITE_FRAME_WAIT_READ_FRAME_CMD         (BLACKBOARD_CMD_OFFSET+35)
typedef struct {
#define RPC_API_WRITE_FRAME_WAIT_READ_FRAME_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t Offset_int32_Write_Vids;\
    int32_t Offset_int8_Write_PhysOrRaw;\
    int32_t Offset_double_Write_Values;\
    int32_t WriteSize;\
    int32_t Offset_int32_Read_Vids;\
    int32_t Offset_int8_Read_PhysOrRaw;\
    int32_t ReadSize;\
    char Data[1];  // > 1Byte!
    RPC_API_WRITE_FRAME_WAIT_READ_FRAME_MESSAGE_MEMBERS
} RPC_API_WRITE_FRAME_WAIT_READ_FRAME_MESSAGE;

typedef struct {
#define RPC_API_WRITE_FRAME_WAIT_READ_FRAME_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    int32_t Offset_double_Read_ValuesRet;\
    int32_t ReadSize;\
    char Data[1];  // > 1Byte!
    RPC_API_WRITE_FRAME_WAIT_READ_FRAME_MESSAGE_ACK_MEMBERS
} RPC_API_WRITE_FRAME_WAIT_READ_FRAME_MESSAGE_ACK;



#define RPC_API_REFERENCE_SYMBOL_CMD         (BLACKBOARD_CMD_OFFSET+36)
typedef struct {
#define RPC_API_REFERENCE_SYMBOL_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetSymbol;\
    int32_t OffsetDisplayName;\
    int32_t OffsetProcess;\
    int32_t OffsetUnit;\
    int ConversionType;\
    int32_t OffsetConversion;\
    double Min;\
    double Max;\
    int Color;\
    int Width;\
    int Precision;\
    int Flags;\
    char Data[1];  // > 1Byte!
    RPC_API_REFERENCE_SYMBOL_MESSAGE_MEMBERS
} RPC_API_REFERENCE_SYMBOL_MESSAGE;

typedef struct {
#define RPC_API_REFERENCE_SYMBOL_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_REFERENCE_SYMBOL_MESSAGE_ACK_MEMBERS
} RPC_API_REFERENCE_SYMBOL_MESSAGE_ACK;

#define RPC_API_DEREFERENCE_SYMBOL_CMD         (BLACKBOARD_CMD_OFFSET+37)
typedef struct {
#define RPC_API_DEREFERENCE_SYMBOL_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int32_t OffsetSymbol;\
    int32_t OffsetProcess;\
    int Flags;\
    char Data[1];  // > 1Byte!
    RPC_API_DEREFERENCE_SYMBOL_MESSAGE_MEMBERS
} RPC_API_DEREFERENCE_SYMBOL_MESSAGE;

typedef struct {
#define RPC_API_DEREFERENCE_SYMBOL_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_DEREFERENCE_SYMBOL_MESSAGE_ACK_MEMBERS
} RPC_API_DEREFERENCE_SYMBOL_MESSAGE_ACK;

#define RPC_API_GET_RAW_CMD         (BLACKBOARD_CMD_OFFSET+38)
typedef struct {
#define RPC_API_GET_RAW_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int Vid;\
    char Data[1];  // > 1Byte!
    RPC_API_GET_RAW_MESSAGE_MEMBERS
} RPC_API_GET_RAW_MESSAGE;

typedef struct {
#define RPC_API_GET_RAW_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;\
    union BB_VARI Value;
    RPC_API_GET_RAW_MESSAGE_ACK_MEMBERS
} RPC_API_GET_RAW_MESSAGE_ACK;

#define RPC_API_SET_RAW_CMD         (BLACKBOARD_CMD_OFFSET+39)
typedef struct {
#define RPC_API_SET_RAW_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
    int Vid;\
    int Type;\
    union BB_VARI Value;\
    int Flags;
    RPC_API_SET_RAW_MESSAGE_MEMBERS
} RPC_API_SET_RAW_MESSAGE;

typedef struct {
#define RPC_API_SET_RAW_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_SET_RAW_MESSAGE_ACK_MEMBERS
} RPC_API_SET_RAW_MESSAGE_ACK;

#define RPC_API_EXPORT_A2L_MEASUREMENT_LIST_CMD         (BLACKBOARD_CMD_OFFSET+41)
typedef struct {
#define RPC_API_EXPORT_A2L_MEASUREMENT_LIST_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
        int32_t OffsetRefList;\
        int32_t OffsetProcess;\
        char Data[1];  // > 1Byte!
    RPC_API_EXPORT_A2L_MEASUREMENT_LIST_MESSAGE_MEMBERS
} RPC_API_EXPORT_A2L_MEASUREMENT_LIST_MESSAGE;

typedef struct {
#define RPC_API_EXPORT_A2L_MEASUREMENT_LIST_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_EXPORT_A2L_MEASUREMENT_LIST_MESSAGE_ACK_MEMBERS
} RPC_API_EXPORT_A2L_MEASUREMENT_LIST_MESSAGE_ACK;

#define RPC_API_IMPORT_A2L_MEASUREMENT_LIST_CMD         (BLACKBOARD_CMD_OFFSET+42)
typedef struct {
#define RPC_API_IMPORT_A2L_MEASUREMENT_LIST_MESSAGE_MEMBERS \
    RPC_API_BASE_MESSAGE Header;\
        int32_t OffsetRefList;\
        int32_t OffsetProcess;\
        char Data[1];  // > 1Byte!
    RPC_API_IMPORT_A2L_MEASUREMENT_LIST_MESSAGE_MEMBERS
} RPC_API_IMPORT_A2L_MEASUREMENT_LIST_MESSAGE;

typedef struct {
#define RPC_API_IMPORT_A2L_MEASUREMENT_LIST_MESSAGE_ACK_MEMBERS \
    RPC_API_BASE_MESSAGE_ACK Header;
    RPC_API_IMPORT_A2L_MEASUREMENT_LIST_MESSAGE_ACK_MEMBERS
} RPC_API_IMPORT_A2L_MEASUREMENT_LIST_MESSAGE_ACK;

#pragma pack(pop)
#ifdef _WIN32
#ifdef __GNUC__
#pragma ms_struct reset
#endif
#endif
int AddBlackboardFunctionToTable(void);


#endif // RPCFUNCBLACKBOARD_H
