name: Build OpenXilEnv - Linux (Python 3.11 + GCC + Qt 6.4.2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: openxilenv
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build gcc g++
        sudo apt install libglx-dev libgl1-mesa-dev
        
    - name: Display GITHUB_WORKSPACE
      run: |
        echo "=== GITHUB_WORKSPACE ==="
        echo $GITHUB_WORKSPACE
        echo ""
        echo "=== Contents of GITHUB_WORKSPACE ==="
        ls -la $GITHUB_WORKSPACE
        echo ""
        
    - name: Install aqtinstall
      run: pip install aqtinstall
  
    - name: Install Qt 6.4.2
      run: |
        aqt install-qt linux desktop 6.4.2 gcc_64 -O $GITHUB_WORKSPACE/Qt
        echo ""
        ls -la $GITHUB_WORKSPACE/Qt/6.4.2
        echo ""
        echo "$GITHUB_WORKSPACE/Qt/6.4.2/gcc_64/bin" >> $GITHUB_PATH
        echo "Qt6_DIR=$GITHUB_WORKSPACE/Qt/6.4.2/gcc_64" >> $GITHUB_ENV
    
    - name: Verify Qt installation
      run: |
        echo "=== Qt Installation Location ==="
        echo "Qt6_DIR: $Qt6_DIR"
        echo ""
        echo "=== Qt Directory Contents ==="
        ls -la $Qt6_DIR
        echo ""
        echo "=== Qt bin Directory ==="
        ls -la $Qt6_DIR/bin
        echo ""
        echo "=== Qt CMake Files ==="
        find $Qt6_DIR -name "Qt6Config.cmake" 2>/dev/null || echo "Qt6Config.cmake not found"
        echo ""
        echo "=== Qt Environment Variables ==="
        env | grep -i qt || echo "No Qt variables set"
        
    - name: Prepare OpenXilEnv Build
      run: |
        cd $GITHUB_WORKSPACE
        mkdir openxilenv-build
        cd openxilenv-build
        cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/tools/OpenXilEnv ../openxilenv

    - name: Build OpenXilEnv
      run: |
        cd $GITHUB_WORKSPACE/openxilenv-build
        cmake --build .

    - name: Install OpenXilEnv 
      run: |
        cd $GITHUB_WORKSPACE/openxilenv-build
        cmake --install .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenXilEnv-Linux-Qt6_4_2
        path: ~/tools/OpenXilEnv/**

